easy_admin:
    site_name: 'Symfony-workplace EasyAdmin'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - 'admin/form.html.twig'
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        Task:
            class: App\Entity\Task
            list:
                fields:
                    - description
                    - duration
                    - user
                    - { property: 'attachment', template: 'vich/task_attachment.html.twig' }
            show:
                fields:
                    - description
                    - duration
                    - user
                    - { property: 'attachment', template: 'vich/task_attachment.html.twig' }
            form:
                fields:
                    - description
                    - duration
                    - user
                    - { property: 'attachmentFile', type: 'vich_file' }
