fos_comment:
    db_driver: orm
    class:
        model:
            comment: App\Entity\Comment
            thread: App\Entity\Thread
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: foscomment.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: ROLE_USER
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
