# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        # the name of the "filter set"
        task_image_100x100:
            data_loader: task_image_loader
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

    loaders:
        task_image_loader:
            filesystem:
                bundle_resources:
                    enabled: true
                data_root: '%kernel.project_dir%/uploads%app.path.task_images%' #where originals files are stored
