vich_uploader:
    db_driver: orm

    mappings:
        task_file:
            uri_prefix: '/'
            upload_destination: '%kernel.project_dir%/uploads%app.path.task_attachments%'
            namer: Vich\UploaderBundle\Naming\HashNamer
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 2, dirs: 2}
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        image_file:
            uri_prefix: '/'
            upload_destination: '%kernel.project_dir%/uploads%app.path.task_images%'
            namer: Vich\UploaderBundle\Naming\HashNamer
            directory_namer:
                service: vich_uploader.directory_namer_subdir
                options: {chars_per_dir: 2, dirs: 2}
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
